server:
  port: 8081

spring:
  #dubbo
  dubbo:
    server: true
    application:
      name: userprovider
    registry:
      address: zookeeper://39.101.208.99:2181
    protocol:
      name: dubbo
      port: 20881
    scan: com.tcg.userprovider.service.impl
  #mail
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    protocol: smtp
    username: magic_camera2@163.com
    password: HAZPGCDCEDGQKFHB
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/magic_camera?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 19981108
  #redis
  redis:
    database: 0
    host: 139.9.140.136
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    password: 19981108

#mymailsources
multi-mail-sources:
  expire: 300
  mails:
    mail-0:
      default-encoding: UTF-8
      host: smtp.163.com
      protocol: smtp
      username: magic_camera2@163.com
      password: HAZPGCDCEDGQKFHB
    mail-1:
      default-encoding: UTF-8
      host: smtp.qq.com
      protocol: smtp
      username: 2662861200@qq.com
      password: anegvacrvmvzeafg
    mail-2:
      default-encoding: UTF-8
      host: smtp.163.com
      protocol: smtp
      username: magic_camera1@163.com
      password: ZCZAGCCONNQBLLCJ
#JWT
jwt:
  expire: 864000
  secret: sdkjflkajflkdjf